-- MySQL Script generated by MySQL Workbench
-- Sat Apr  5 19:57:51 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema arqueosDb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `arqueosDb` ;

-- -----------------------------------------------------
-- Schema arqueosDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `arqueosDb` DEFAULT CHARACTER SET utf8 ;
USE `arqueosDb` ;

-- -----------------------------------------------------
-- Table `arqueosDb`.`productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `arqueosDb`.`productos` ;

CREATE TABLE IF NOT EXISTS `arqueosDb`.`productos` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `codigo_producto` VARCHAR(4) NULL,
  `nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idproducts_UNIQUE` ON `arqueosDb`.`productos` (`idproducto` ASC) VISIBLE;

CREATE UNIQUE INDEX `codigo_producto_UNIQUE` ON `arqueosDb`.`productos` (`codigo_producto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `arqueosDb`.`sucursales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `arqueosDb`.`sucursales` ;

CREATE TABLE IF NOT EXISTS `arqueosDb`.`sucursales` (
  `idsucursal` INT NOT NULL AUTO_INCREMENT,
  `codigo_sucursal` VARCHAR(5) NULL,
  `nombre` VARCHAR(50) NULL,
  PRIMARY KEY (`idsucursal`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idsucursal_UNIQUE` ON `arqueosDb`.`sucursales` (`idsucursal` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `arqueosDb`.`documentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `arqueosDb`.`documentos` ;

CREATE TABLE IF NOT EXISTS `arqueosDb`.`documentos` (
  `iddocumento` INT NOT NULL AUTO_INCREMENT,
  `codigo_documento` VARCHAR(6) NULL,
  `descripcion` VARCHAR(50) NULL,
  PRIMARY KEY (`iddocumento`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `iddocumento_UNIQUE` ON `arqueosDb`.`documentos` (`iddocumento` ASC) VISIBLE;

CREATE UNIQUE INDEX `codigo_documento_UNIQUE` ON `arqueosDb`.`documentos` (`codigo_documento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `arqueosDb`.`arqueos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `arqueosDb`.`arqueos` ;

CREATE TABLE IF NOT EXISTS `arqueosDb`.`arqueos` (
  `idarqueos` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `diferencia` DECIMAL(15,2) NULL,
  `saldo_final` DECIMAL(15,2) NULL,
  `resultado` ENUM('A', 'B', 'C', 'D') NULL,
  `sucursales_idsucursal` INT NOT NULL,
  `productos_idproducto` INT NOT NULL,
  `documentos_iddocumento` INT NOT NULL,
  PRIMARY KEY (`idarqueos`),
  CONSTRAINT `fk_arqueos_sucursales1`
    FOREIGN KEY (`sucursales_idsucursal`)
    REFERENCES `arqueosDb`.`sucursales` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arqueos_productos1`
    FOREIGN KEY (`productos_idproducto`)
    REFERENCES `arqueosDb`.`productos` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arqueos_documentos1`
    FOREIGN KEY (`documentos_iddocumento`)
    REFERENCES `arqueosDb`.`documentos` (`iddocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idarqueos_UNIQUE` ON `arqueosDb`.`arqueos` (`idarqueos` ASC) VISIBLE;

CREATE INDEX `fk_arqueos_sucursales1_idx` ON `arqueosDb`.`arqueos` (`sucursales_idsucursal` ASC) VISIBLE;

CREATE INDEX `fk_arqueos_productos1_idx` ON `arqueosDb`.`arqueos` (`productos_idproducto` ASC) VISIBLE;

CREATE INDEX `fk_arqueos_documentos1_idx` ON `arqueosDb`.`arqueos` (`documentos_iddocumento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `arqueosDb`.`sucursal_producto_documento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `arqueosDb`.`sucursal_producto_documento` ;

CREATE TABLE IF NOT EXISTS `arqueosDb`.`sucursal_producto_documento` (
  `sucursales_idsucursal` INT NOT NULL,
  `productos_idproducto` INT NOT NULL,
  `documentos_iddocumento` INT NOT NULL,
  PRIMARY KEY (`sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`),
  CONSTRAINT `fk_sucursales_productos_documentos_sucursales`
    FOREIGN KEY (`sucursales_idsucursal`)
    REFERENCES `arqueosDb`.`sucursales` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sucursales_productos_documentos_productos1`
    FOREIGN KEY (`productos_idproducto`)
    REFERENCES `arqueosDb`.`productos` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sucursales_productos_documentos_documentos1`
    FOREIGN KEY (`documentos_iddocumento`)
    REFERENCES `arqueosDb`.`documentos` (`iddocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_sucursales_productos_documentos_sucursales_idx` ON `arqueosDb`.`sucursal_producto_documento` (`sucursales_idsucursal` ASC) VISIBLE;

CREATE INDEX `fk_sucursales_productos_documentos_productos1_idx` ON `arqueosDb`.`sucursal_producto_documento` (`productos_idproducto` ASC) VISIBLE;

CREATE INDEX `fk_sucursales_productos_documentos_documentos1_idx` ON `arqueosDb`.`sucursal_producto_documento` (`documentos_iddocumento` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `arqueosDb`.`arqueos_descuadres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `arqueosDb`.`arqueos_descuadres` ;

CREATE TABLE IF NOT EXISTS `arqueosDb`.`arqueos_descuadres` (
  `idarqueos_descuadres` INT NOT NULL AUTO_INCREMENT,
  `anio` INT NULL,
  `mes` INT NULL,
  `diferencia` DECIMAL(15,2) NULL,
  `sucursales_idsucursal` INT NOT NULL,
  `productos_idproducto` INT NOT NULL,
  `documentos_iddocumento` INT NOT NULL,
  PRIMARY KEY (`idarqueos_descuadres`),
  CONSTRAINT `fk_arqueos_descuadres_sucursales1`
    FOREIGN KEY (`sucursales_idsucursal`)
    REFERENCES `arqueosDb`.`sucursales` (`idsucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arqueos_descuadres_productos1`
    FOREIGN KEY (`productos_idproducto`)
    REFERENCES `arqueosDb`.`productos` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arqueos_descuadres_documentos1`
    FOREIGN KEY (`documentos_iddocumento`)
    REFERENCES `arqueosDb`.`documentos` (`iddocumento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_arqueos_descuadres_sucursales1_idx` ON `arqueosDb`.`arqueos_descuadres` (`sucursales_idsucursal` ASC) VISIBLE;

CREATE INDEX `fk_arqueos_descuadres_productos1_idx` ON `arqueosDb`.`arqueos_descuadres` (`productos_idproducto` ASC) VISIBLE;

CREATE INDEX `fk_arqueos_descuadres_documentos1_idx` ON `arqueosDb`.`arqueos_descuadres` (`documentos_iddocumento` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `arqueosDb`.`productos`
-- -----------------------------------------------------
START TRANSACTION;
USE `arqueosDb`;
INSERT INTO `arqueosDb`.`productos` (`idproducto`, `codigo_producto`, `nombre`) VALUES (DEFAULT, 'PR01', NULL);
INSERT INTO `arqueosDb`.`productos` (`idproducto`, `codigo_producto`, `nombre`) VALUES (DEFAULT, 'PR02', NULL);
INSERT INTO `arqueosDb`.`productos` (`idproducto`, `codigo_producto`, `nombre`) VALUES (DEFAULT, 'PR03', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `arqueosDb`.`sucursales`
-- -----------------------------------------------------
START TRANSACTION;
USE `arqueosDb`;
INSERT INTO `arqueosDb`.`sucursales` (`idsucursal`, `codigo_sucursal`, `nombre`) VALUES (DEFAULT, '00101', 'Sucursal A');
INSERT INTO `arqueosDb`.`sucursales` (`idsucursal`, `codigo_sucursal`, `nombre`) VALUES (DEFAULT, '00102', 'Sucursal B');
INSERT INTO `arqueosDb`.`sucursales` (`idsucursal`, `codigo_sucursal`, `nombre`) VALUES (DEFAULT, '00103', 'Sucursal C');

COMMIT;


-- -----------------------------------------------------
-- Data for table `arqueosDb`.`documentos`
-- -----------------------------------------------------
START TRANSACTION;
USE `arqueosDb`;
INSERT INTO `arqueosDb`.`documentos` (`iddocumento`, `codigo_documento`, `descripcion`) VALUES (DEFAULT, 'DOC001', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `arqueosDb`.`arqueos`
-- -----------------------------------------------------
START TRANSACTION;
USE `arqueosDb`;
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-01-01',  3081673400.00, 0.00, 'C', 1, 1, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-01-01',  0.00, 0.00, 'C', 1, 1, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-01-01',  1.00, 0.00, 'D', 1, 2, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-01-01',  19.00, 19.50, 'B', 1, 3, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-01-01',  150.00, 55.00, 'A', 2, 1, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-01-01',  895714450.00, 0.00, 'C', 2, 2, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-01-01',  422793679, 9.10, 'D', 2, 3, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-01-01',  2976795600.00, 29.00, 'A', 3, 1, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-01-01',  691624500.00, 19.50, 'D', 3, 2, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-02-01',  0.00, 0.00, 'C', 1, 1, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-02-01',  1.00, 0.00, 'C', 1, 2, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-02-01',  19.00, 19.50, 'B', 1, 3, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-02-01',  150.00, 55.00, 'D', 2, 1, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-02-01',  895714450.00, 0.00, 'D', 2, 2, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-02-01',  422793679, 9.10, 'C', 2, 3, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-02-01',  2976795600.00, 29.00, 'A', 3, 1, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-02-01',  691624500.00, 19.50, 'A', 3, 2, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-02-01',  3081673400.00, 0.00, 'B', 3, 3, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-02-01',  0.00, 0.00, 'A', 1, 1, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-03-01',  1.00, 0.00, 'B', 1, 2, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-03-01',  19.00, 19.50, 'A', 1, 3, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-03-01',  150.00, 55.00, 'D', 2, 1, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-03-01',  895714450.00, 0.00, 'D', 2, 2, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-03-01',  422793679.00, 9.10, 'C', 2, 3, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-03-01',  2976795600.00, 29.00, 'A', 3, 1, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-03-01',  691624500.00, 19.50, 'C', 3, 2, 1);
INSERT INTO `arqueosDb`.`arqueos` (`idarqueos`, `fecha`, `diferencia`, `saldo_final`, `resultado`, `sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (NULL, '2025-03-01',  3081673400.00, 0.00, 'B', 3, 3, 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `arqueosDb`.`sucursal_producto_documento`
-- -----------------------------------------------------
START TRANSACTION;
USE `arqueosDb`;
INSERT INTO `arqueosDb`.`sucursal_producto_documento` (`sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (1, 1, 1);
INSERT INTO `arqueosDb`.`sucursal_producto_documento` (`sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (1, 2, 1);
INSERT INTO `arqueosDb`.`sucursal_producto_documento` (`sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (1, 3, 1);
INSERT INTO `arqueosDb`.`sucursal_producto_documento` (`sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (2, 1, 1);
INSERT INTO `arqueosDb`.`sucursal_producto_documento` (`sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (2, 2, 1);
INSERT INTO `arqueosDb`.`sucursal_producto_documento` (`sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (2, 3, 1);
INSERT INTO `arqueosDb`.`sucursal_producto_documento` (`sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (3, 1, 1);
INSERT INTO `arqueosDb`.`sucursal_producto_documento` (`sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (3, 2, 1);
INSERT INTO `arqueosDb`.`sucursal_producto_documento` (`sucursales_idsucursal`, `productos_idproducto`, `documentos_iddocumento`) VALUES (3, 3, 1);

COMMIT;

